language: node_js
node_js:
    - "4"
    - "6"

before_script:
    - npm install -g grunt-cli

script:
    - grunt lint
    - node run_tests

after_success:
    - npm install istanbul codecov
    - ./node_modules/.bin/istanbul cover run_tests
    - ./node_modules/.bin/codecov

sudo: false
